import os
import datetime
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from pydicom.dataset import Dataset
from pydicom.sequence import Sequence
from pydicom.uid import generate_uid

app = FastAPI()

# Validation of input data

class WorklistRequest(BaseModel):
    patient_name: str
    patient_id: str
    accession_number: str
    patient_sex: str = "O"  # Default: Other
    patient_birthdate: str = "19800101" # Format YYYYMMDD
    modality: str = "MR"
    scheduled_ae_title: str = "MRISCANNER" # Must match the modality AE Title
    study_description: str = "MRI Head"


# endpoint to create a worklist file
@app.post("/create-worklist")
def create_worklist(item: WorklistRequest):
    ''' Try to create a DICOM worklist file based on the provided data '''
    try:
        # 1. Basic DICOM dataset creation
        ds = Dataset()
        ds.is_little_endian = True # de-facto standard for modern DICOM. see also: https://en.wikipedia.org/wiki/Endianness
        # VR stands for Value Representation. The following line tells the DICOM library to explicitly indicate
        # which data type is used for each data element. This is the most common format, btw.
        ds.is_implicit_VR = False 
        
        # 2. Header standard - these are the attributes on the top level of the DICOM file - the "file" level
        ds.SpecificCharacterSet = "ISO_IR 100" # Latin alphabet and accented characters like é, è, à, ü, etc.
        # This is the actual attribute related to Modality Worklist Information Model - FIND - see also https://www.dicomlibrary.com/dicom/sop/
        # Should you change the SOP Class UID, it's likely that the data will be interpreted differently (e.g.: images, etc) by the receiving system.
        ds.SOPClassUID = "1.2.840.10008.5.1.4.31"
        # Unique identifier generated by the library for this specific instance of the worklist
        ds.SOPInstanceUID = generate_uid()
        
        # 3. Patient Data - these attributes belong to the patient "level"
        # Fill in patient-related data, as provided through the API request
        ds.PatientName = item.patient_name
        ds.PatientID = item.patient_id
        ds.PatientSex = item.patient_sex
        ds.PatientBirthDate = item.patient_birthdate
        
        # 4. Study/Request Data - these attributes belong to the study/request "level"
        # Fill in study-related data, as provided through the API request
        ds.AccessionNumber = item.accession_number
        ds.StudyInstanceUID = generate_uid()
        ds.RequestedProcedureDescription = item.study_description
        
        # 5. Scheduled Procedure Step Sequence - within the study "level", we have a sequence of scheduled procedure steps
        # A DICOM entity can have multiple scheduled procedure steps. See also https://www.medicalconnections.co.uk/kb/dicom-sequences/
        # E.g.: in a CT scan with multiple projections: Frontal, Lateral, etc each 
        # projection can be a separate scheduled procedure step. Here we create one single step.
        # To do so, we create a new Dataset for the step and fill in the relevant data.
        # This has nothing to do with "MR sequences" used in MRI imaging.
        step = Dataset()
        step.ScheduledStationAETitle = item.scheduled_ae_title # Must match the AE Title of the modality
        step.Modality = item.modality
        step.ScheduledProcedureStepStartDate = datetime.datetime.now().strftime('%Y%m%d')
        step.ScheduledProcedureStepStartTime = datetime.datetime.now().strftime('%H%M%S')
        # Using Accession Number as SPS ID
        step.ScheduledProcedureStepID = item.accession_number  
        step.ScheduledProcedureStepDescription = item.study_description
        
        # Let's insert the step into a sequence, using the pydicom Sequence class
        ds.ScheduledProcedureStepSequence = Sequence([step])

        # 6. Save the worklist file
        filename = f"/shared_data/{item.accession_number}.wl"
        ds.save_as(filename, write_like_original=False)
        
        return {
            "message": "Worklist created successfully", 
            "file": filename,
            "data": item
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))